#!/usr/bin/env python
"""Draw fresh, never-seen ImageNet candidate pools for the Phase B holdout.

Reuses make_cases.py's exact mechanism (`ragregen.casegen.rank_classes`, the
same ImageNet val parquet, the same `imagenet_coarse.yaml` pool) but against
an exclusion set extended to cover every concept already used anywhere in
this project (the 22-case bridge set, the 70-case ImageNet "common" cohort,
and the 24-concept hybrid-verifier holdout) -- design section 3's
requirement that Phase B touch nothing any prior v1/v2/v3/Phase A work has
seen.

Two candidate pools, from the SAME exclude set and the SAME groundable class
pool, ranked in OPPOSITE directions:

- **control**: `casegen.rank_classes` as-is -- the most corpus-frequent
  classes (FLUX should already render these correctly).
- **rare**: the LEAST corpus-frequent classes that can still serve
  REFS_PER_CASE references -- an unvalidated PROXY for "fine-grained concept
  FLUX gets wrong", not a guarantee. Oversampled heavily (`--n-rare`)
  because the true FAIL yield of this heuristic is unknown until
  hand-labelled; any shortfall against the 24-judgeable-FAIL floor needs a
  human-curated supplement (design section 3's replacement reserve), not
  just a bigger n.

This script only selects concepts and downloads their held-out reference
images -- no GPU, no drafting. Screening (drafting + hand identity
labelling) is a separate, deliberate next step.
"""
from __future__ import annotations

import argparse
import io
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import yaml  # noqa: E402

from ragregen import casegen, config, env  # noqa: E402
from scripts.make_cases import (  # noqa: E402
    IMAGENET_REPO, IMAGENET_VAL, REFS_PER_CASE, _check_shortfall,
    _class_names, _resolve_label_ids)


def _emit_yaml(entries, images_root: Path, name: str) -> str:
    """Like make_cases.emit_yaml, but with a name that identifies this file
    (make_cases.emit_yaml hardcodes "laion_common_v1", which would collide
    with the existing 92-case dataset_common.yaml's own header)."""
    doc = {"name": name, "images_root": str(images_root), "cases": list(entries)}
    header = (
        f"# Generated by scripts/make_phase_b_candidates.py. Do not hand-edit;\n"
        f"# re-run instead, or the seed no longer describes the set.\n"
        f"#\n"
        f"# UNJUDGED candidates -- draft + hand-label before freezing any\n"
        f"# Phase B holdout cohort from this pool (design section 3).\n\n")
    return header + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True)


def _rank_rare(counts: dict, coarse_map: dict, *, exclude: set,
              already_chosen: set, n: int, min_count: int) -> list[str]:
    """The `n` LEAST common groundable classes, excluding `exclude` and
    whatever `--n-control` already claimed. Mirrors `casegen.rank_classes`'s
    tie-break (alphabetical) but sorts ascending instead of descending."""
    pool = [c for c in coarse_map
           if c not in exclude and c not in already_chosen
           and counts.get(c, 0) >= min_count]
    pool.sort(key=lambda c: (int(counts.get(c, 0)), c))
    return pool[:n]


def _excluded_concepts(paths: list[Path]) -> set[str]:
    excluded = set()
    for path in paths:
        if not path.is_file():
            continue
        ds = config.load_dataset(path)
        excluded |= {c.concept.lower() for c in ds.cases}
    return excluded


def _download_refs(chosen: list[str]) -> dict[str, list[bytes]]:
    import pyarrow.parquet as pq
    from huggingface_hub import hf_hub_download

    wanted = {c: [] for c in chosen}
    for shard in IMAGENET_VAL:
        local = hf_hub_download(IMAGENET_REPO, shard, repo_type="dataset")
        pf = pq.ParquetFile(local)
        names = _class_names(pf.schema_arrow)
        want_ids, missing, ambiguous = _resolve_label_ids(names, chosen)
        for concept, collided in ambiguous:
            print(f"[phase-b-candidates] WARNING: {concept!r} matches "
                 f"{len(collided)} labels {collided} -- taking the first",
                 flush=True)
        _check_shortfall(chosen, missing, allow_short=len(chosen))
        for batch in pf.iter_batches(batch_size=512, columns=["image", "label"]):
            for img, label in zip(batch.column("image").to_pylist(),
                                  batch.column("label").to_pylist()):
                concept = want_ids.get(int(label))
                if concept is None or len(wanted[concept]) >= REFS_PER_CASE:
                    continue
                wanted[concept].append(img["bytes"])
    return wanted


def _emit(chosen: list[str], wanted: dict, coarse_map: dict, *,
          kind: str, cohort: str, name: str, refs_dir: Path) -> list[dict]:
    from PIL import Image

    refs_dir.mkdir(parents=True, exist_ok=True)
    entries = []
    for i, concept in enumerate(chosen):
        blobs = wanted[concept]
        if len(blobs) < REFS_PER_CASE:
            print(f"[phase-b-candidates] skipping {concept!r}: only "
                 f"{len(blobs)} refs")
            continue
        cid = concept.replace(" ", "_").replace("-", "_").replace("'", "")
        d = refs_dir / cid
        d.mkdir(parents=True, exist_ok=True)
        refs = []
        for j, blob in enumerate(blobs):
            path = d / f"{cid}_{j}.jpg"
            Image.open(io.BytesIO(blob)).convert("RGB").save(path, quality=95)
            refs.append(f"{cid}/{path.name}")
        entries.append({
            "id": cid, "prompt": casegen.frame_prompt(concept, i),
            "concept": concept, "coarse": coarse_map[concept],
            "kind": kind, "cohort": cohort, "gt_refs": refs,
        })
    return entries


def main() -> int:
    env.setup()
    root = env.PROJECT_ROOT

    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", type=Path,
                    default=root / "data/laion100k/corpus_manifest.json")
    ap.add_argument("--coarse", type=Path,
                    default=root / "configs/imagenet_coarse.yaml")
    ap.add_argument("--exclude-datasets", type=Path, nargs="+", default=[
        root / "configs/dataset.yaml",
        root / "configs/dataset_common.yaml",
        root / "configs/dataset_verifier_holdout.yaml"])
    ap.add_argument("--refs-dir", type=Path,
                    default=root / "data/gt_refs_phase_b")
    ap.add_argument("--out-control", type=Path,
                    default=root / "configs/dataset_phase_b_control_candidates.yaml")
    ap.add_argument("--out-rare", type=Path,
                    default=root / "configs/dataset_phase_b_rare_candidates.yaml")
    ap.add_argument("--n-control", type=int, default=32)
    ap.add_argument("--n-rare", type=int, default=72)
    args = ap.parse_args()

    if args.out_control.exists() or args.out_rare.exists():
        raise FileExistsError(
            f"refusing to overwrite an existing candidate file: "
            f"{args.out_control} / {args.out_rare}")

    counts = json.loads(args.manifest.read_text())["per_concept"]
    coarse_map = yaml.safe_load(args.coarse.read_text())
    exclude = _excluded_concepts(args.exclude_datasets)
    print(f"[phase-b-candidates] {len(exclude)} concepts excluded (already "
         f"used by v1/v2/v3/Phase A)")

    chosen_control = casegen.rank_classes(
        counts, coarse_map, exclude=exclude, n=args.n_control,
        min_count=REFS_PER_CASE)
    chosen_rare = _rank_rare(
        counts, coarse_map, exclude=exclude, already_chosen=set(chosen_control),
        n=args.n_rare, min_count=REFS_PER_CASE)
    print(f"[phase-b-candidates] {len(chosen_control)} control candidates, "
         f"{len(chosen_rare)} rare candidates chosen")

    wanted = _download_refs(chosen_control + chosen_rare)

    control_entries = _emit(
        chosen_control, wanted, coarse_map, kind="control", cohort="common",
        name="phase_b_control_candidates", refs_dir=args.refs_dir)
    rare_entries = _emit(
        chosen_rare, wanted, coarse_map, kind="target", cohort="common",
        name="phase_b_rare_candidates", refs_dir=args.refs_dir)

    args.out_control.write_text(_emit_yaml(
        control_entries, images_root=args.refs_dir, name="phase_b_control_candidates"))
    args.out_rare.write_text(_emit_yaml(
        rare_entries, images_root=args.refs_dir, name="phase_b_rare_candidates"))
    print(f"[phase-b-candidates] {len(control_entries)} control -> {args.out_control}")
    print(f"[phase-b-candidates] {len(rare_entries)} rare -> {args.out_rare}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
