#!/usr/bin/env python
"""Emit the frozen local holdout used to validate the hybrid verifier."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from ragregen import config, env  # noqa: E402


# id, display name, prompt, groundable coarse term
RARE_CASES = (
    ("lagotto_romagnolo", "Lagotto Romagnolo",
     "a Lagotto Romagnolo standing beside a quiet lake", "dog"),
    ("xoloitzcuintli", "Xoloitzcuintli",
     "a Xoloitzcuintli standing in warm afternoon light", "dog"),
    ("azawakh", "Azawakh",
     "an Azawakh running across a dry grassland", "dog"),
    ("bergamasco_shepherd", "Bergamasco Shepherd",
     "a Bergamasco Shepherd standing on a mountain path", "dog"),
    ("khachapuri", "khachapuri",
     "an Adjarian khachapuri on a wooden dining table", "bread"),
    ("salak", "salak",
     "several salak fruits arranged in a market basket", "fruit"),
    ("cherimoya", "cherimoya",
     "a cherimoya resting on a ceramic plate", "fruit"),
    ("hakka_tulou", "Hakka tulou",
     "a Hakka tulou surrounded by green hills", "building"),
    ("stave_church", "stave church",
     "a Norwegian stave church in a snowy valley", "building"),
    ("trullo", "trullo",
     "a traditional trullo beneath a clear blue sky", "building"),
    ("okapi", "okapi",
     "an okapi walking through a forest clearing", "giraffe"),
    ("saiga_antelope", "saiga antelope",
     "a saiga antelope standing on the open steppe", "antelope"),
)

# id, asset directory, display name, prompt, groundable coarse term
CONTROL_CASES = (
    ("apple", "apple_fruit", "apple",
     "a red apple resting on a wooden table", "fruit"),
    ("barn", "barn_building", "barn",
     "a red barn in a green field", "building"),
    ("church", "church_building", "church",
     "a stone church in a quiet village", "building"),
    ("daisy", "daisy_flower", "daisy",
     "a daisy blooming in a summer garden", "flower"),
    ("deer", "deer", "deer",
     "a deer standing at the edge of a forest", "animal"),
    ("donkey", "donkey", "donkey",
     "a donkey walking along a country path", "animal"),
    ("labrador_retriever", "labrador_retriever", "Labrador Retriever",
     "a Labrador Retriever sitting on a green lawn", "dog"),
    ("lizard", "lizard_on_a_rock", "lizard",
     "a lizard resting on a sunlit rock", "reptile"),
    ("pine_tree", "pine_tree", "pine tree",
     "a pine tree on a windswept hillside", "tree"),
    ("pizza", "pizza", "pizza",
     "a pizza served on a wooden board", "food"),
    ("stone_cottage", "stone_cottage", "stone cottage",
     "a stone cottage beside a country lane", "building"),
    ("tiger", "tiger", "tiger",
     "a tiger walking through tall grass", "big cat"),
)


def _refs(folder: Path, expected: int, case_id: str) -> list[str]:
    paths = sorted(folder.glob("wm_*"))
    if len(paths) != expected:
        raise ValueError(
            f"{case_id}: expected {expected} references, found {len(paths)} "
            f"under {folder}")
    return [str(path.resolve()) for path in paths]


def build_entries(rare_root: Path, control_root: Path):
    rare = [
        {"id": case_id, "prompt": prompt, "concept": concept,
         "coarse": coarse, "kind": "target", "cohort": "bridge",
         "gt_refs": _refs(Path(rare_root) / case_id, 4, case_id)}
        for case_id, concept, prompt, coarse in RARE_CASES
    ]
    controls = [
        {"id": case_id, "prompt": prompt, "concept": concept,
         "coarse": coarse, "kind": "control",
         "cohort": "common",
         "gt_refs": _refs(Path(control_root) / folder, 3, case_id)}
        for case_id, folder, concept, prompt, coarse in CONTROL_CASES
    ]
    return rare, controls


def emit_dataset(name: str, entries: list[dict]) -> str:
    document = {"name": name, "images_root": "/", "cases": entries}
    header = (
        "# Generated by scripts/make_verifier_holdout.py. Do not hand-edit.\n"
        "# Frozen by docs/superpowers/specs/"
        "2026-08-18-hybrid-verifier-validation-design.md.\n\n")
    return header + yaml.safe_dump(document, sort_keys=False,
                                   allow_unicode=True)


def main(argv=None) -> int:
    root = env.PROJECT_ROOT
    ap = argparse.ArgumentParser()
    ap.add_argument("--rare-root", type=Path,
                    default=root.parent / "rag-edit/data/images")
    ap.add_argument("--control-root", type=Path,
                    default=root.parent / "rag-edit/data/scenes")
    ap.add_argument("--output-dir", type=Path,
                    default=root / "configs")
    args = ap.parse_args(argv)

    rare, controls = build_entries(args.rare_root, args.control_root)
    outputs = (
        ("dataset_verifier_holdout.yaml", "verifier_holdout_v1",
         rare + controls),
        ("dataset_verifier_holdout_rare.yaml", "verifier_holdout_rare_v1",
         rare),
        ("dataset_verifier_holdout_control.yaml",
         "verifier_holdout_control_v1", controls),
    )
    args.output_dir.mkdir(parents=True, exist_ok=True)
    for filename, name, entries in outputs:
        path = args.output_dir / filename
        path.write_text(emit_dataset(name, entries))
        loaded = config.load_dataset(path)
        if len(loaded.cases) != len(entries):
            raise RuntimeError(
                f"{path}: emitted {len(entries)} cases but loaded "
                f"{len(loaded.cases)}")
        print(f"[holdout] {len(entries)} cases -> {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
