#!/usr/bin/env python
"""ImageNet -> the 92-case set. Doc 5 §5.

ImageNet does two jobs here, both OUTSIDE the pipeline: class names become
prompts, and three val images per class become the held-out answer key. The
pipeline never sees these images -- validate.py:88 refuses to run if they ever
land inside the retrieval corpus.

Usage: ./scripts/run.sh make-cases
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import argparse  # noqa: E402
import io  # noqa: E402
import json  # noqa: E402

import yaml  # noqa: E402

from ragregen import casegen, config, env  # noqa: E402

IMAGENET_REPO = "evanarlian/imagenet_1k_resized_256"
IMAGENET_VAL = [
    "data/val-00000-of-00002-b5248be478d25e41.parquet",
    "data/val-00001-of-00002-85f3d9c8fa1edb63.parquet",
]
REFS_PER_CASE = 3


def emit_yaml(entries, images_root: Path) -> str:
    """The dataset YAML. Round-trips through config.load_dataset unchanged."""
    doc = {
        "name": "laion_common_v1",
        "images_root": str(images_root),
        "cases": list(entries),
    }
    header = (
        "# Generated by scripts/make_cases.py -- doc 5 §5. Do not hand-edit;\n"
        "# re-run make-cases instead, or the seed no longer describes the set.\n"
        "#\n"
        "# cohort: bridge = the 22 legacy cases, full-resolution gt_refs.\n"
        "# cohort: common = ImageNet-derived, 256px gt_refs.\n"
        "# The report never averages DINO across the two.\n\n")
    return header + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True)


def _class_names(schema) -> list[str]:
    """Label index -> class name, from the parquet's HuggingFace metadata."""
    meta = json.loads(schema.metadata[b"huggingface"].decode())
    feature = meta["info"]["features"]["label"]
    return list(feature["names"])


def _lemmas(name: str) -> list[str]:
    """Every lemma in an ImageNet class name, normalised.

    492 of the parquet's 1000 ClassLabel names are comma-separated synonym
    lists, and configs/imagenet_coarse.yaml does not always name a class by
    its FIRST lemma: its key for label 437 is `lighthouse`, the second lemma
    of "beacon, lighthouse, beacon light, pharos". Indexing the first lemma
    alone silently drops those classes.
    """
    return [p.strip().lower() for p in name.split(",") if p.strip()]


def _normalise_class_name(name: str) -> str:
    """The comparable form of an ImageNet class name.

    HuggingFace `ClassLabel` names for ImageNet are the full comma-separated
    synset lemma string ("hammerhead, hammerhead shark"), while
    configs/imagenet_coarse.yaml's keys are the first lemma alone
    ("hammerhead"). Matching the two verbatim silently resolves neither, so
    both sides are reduced to first-lemma-lowercase before comparison. A
    parquet that already uses the short form normalises to itself.
    """
    return name.split(",")[0].strip().lower()


def _resolve_label_ids(names, chosen):
    """(label id -> chosen class, unresolved classes, ambiguous classes).

    `names` is the parquet's label vocabulary in label-id order, so the index
    into it IS the label id -- the mapping the batch loop looks up. Returns
    the misses rather than dropping them: a chosen class that never resolves
    means the case set is short, and that has to reach the caller as a
    failure rather than as one print line (doc 5 §5).

    `ambiguous` carries any chosen class whose normalised form matches more
    than one label. The first id wins, deterministically, but the collision is
    returned so the caller can say so -- two distinct ImageNet classes folded
    into one prompt is not something to discover from the refs.
    """
    #: Two indexes, not one. A concept that IS some class's first lemma must
    #: never be hijacked by another class that merely lists it as a synonym,
    #: so the primary index wins and the alias index is only a fallback.
    primary: dict[str, list[int]] = {}
    alias: dict[str, list[int]] = {}
    for i, name in enumerate(names):
        lemmas = _lemmas(name)
        if not lemmas:
            continue
        primary.setdefault(lemmas[0], []).append(i)
        for lemma in lemmas:
            alias.setdefault(lemma, []).append(i)

    want_ids: dict[int, str] = {}
    missing: list[str] = []
    ambiguous: list[tuple[str, list[str]]] = []
    for concept in chosen:
        key = _normalise_class_name(concept)
        ids = primary.get(key) or alias.get(key)
        if not ids:
            missing.append(concept)
            continue
        if len(ids) > 1:
            ambiguous.append((concept, [names[i] for i in ids]))
        want_ids[ids[0]] = concept
    return want_ids, missing, ambiguous


def _check_shortfall(chosen, missing, allow_short: int) -> None:
    """Refuse to emit a truncated case set. Raises SystemExit.

    The failure this prevents: unresolved classes cost one print line each,
    `main()` still writes a valid-looking dataset_common.yaml holding only the
    22 bridge cases, `validate` passes it, and the operator learns that
    `control/common` has n=0 after ~18 hours of booked card time.
    """
    if len(missing) <= allow_short:
        return
    raise SystemExit(
        f"[make-cases] {len(missing)}/{len(chosen)} chosen classes did not "
        f"resolve to an ImageNet label: {', '.join(missing[:10])}"
        f"{' ...' if len(missing) > 10 else ''}. This is a class-name format "
        f"mismatch between configs/imagenet_coarse.yaml and the parquet's "
        f"ClassLabel names -- fix it before running the campaign, or pass "
        f"--allow-short {len(missing)} if these classes genuinely are not in "
        f"the parquet.")


def _bridge_entries(ds) -> list[dict]:
    """The 22 legacy cases, carried forward verbatim with their own refs."""
    out = []
    for case in ds.cases:
        out.append({
            "id": case.id,
            "prompt": case.prompt,
            "concept": case.concept,
            "coarse": case.coarse,
            "kind": case.kind,
            "cohort": "bridge",
            "gt_refs": [str(p) for p in case.gt_refs],
        })
    return out


def main() -> int:
    env.setup()
    root = env.PROJECT_ROOT

    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", type=Path,
                    default=root / "data/laion100k/corpus_manifest.json")
    ap.add_argument("--coarse", type=Path,
                    default=root / "configs/imagenet_coarse.yaml")
    ap.add_argument("--bridge", type=Path,
                    default=config.DEFAULT_DATASET_PATH)
    ap.add_argument("--refs-dir", type=Path, default=root / "data/gt_refs")
    ap.add_argument("--out", type=Path,
                    default=root / "configs/dataset_common.yaml")
    ap.add_argument("--n", type=int, default=70)
    ap.add_argument("--allow-short", dest="allow_short", type=int, default=0,
                    help="tolerate up to N chosen classes that do not resolve "
                         "to an ImageNet label (default 0: any shortfall is "
                         "an error)")
    args = ap.parse_args()

    import pyarrow.parquet as pq
    from huggingface_hub import hf_hub_download
    from PIL import Image

    counts = json.loads(args.manifest.read_text())["per_concept"]
    coarse_map = yaml.safe_load(args.coarse.read_text())
    bridge = config.load_dataset(args.bridge)
    exclude = {c.concept.lower() for c in bridge.cases}

    chosen = casegen.rank_classes(counts, coarse_map, exclude=exclude,
                                  n=args.n, min_count=REFS_PER_CASE)
    print(f"[make-cases] {len(chosen)} common classes chosen", flush=True)

    wanted = {c: [] for c in chosen}
    for shard in IMAGENET_VAL:
        local = hf_hub_download(IMAGENET_REPO, shard, repo_type="dataset")
        pf = pq.ParquetFile(local)
        names = _class_names(pf.schema_arrow)
        want_ids, missing, ambiguous = _resolve_label_ids(names, chosen)
        for concept, collided in ambiguous:
            print(f"[make-cases] WARNING: {concept!r} matches "
                  f"{len(collided)} labels {collided} -- taking the first",
                  flush=True)
        _check_shortfall(chosen, missing, args.allow_short)
        for batch in pf.iter_batches(batch_size=512,
                                     columns=["image", "label"]):
            for img, label in zip(batch.column("image").to_pylist(),
                                  batch.column("label").to_pylist()):
                concept = want_ids.get(int(label))
                if concept is None or len(wanted[concept]) >= REFS_PER_CASE:
                    continue
                wanted[concept].append(img["bytes"])

    entries = _bridge_entries(bridge)
    args.refs_dir.mkdir(parents=True, exist_ok=True)
    for i, concept in enumerate(chosen):
        blobs = wanted[concept]
        if len(blobs) < REFS_PER_CASE:
            #: Fewer than three refs cannot survive the held-out split, so the
            #: case is dropped here rather than raising hours into a run.
            print(f"[make-cases] skipping {concept!r}: only {len(blobs)} refs")
            continue
        cid = concept.replace(" ", "_").replace("-", "_").replace("'", "")
        d = args.refs_dir / cid
        d.mkdir(parents=True, exist_ok=True)
        refs = []
        for j, blob in enumerate(blobs):
            path = d / f"{cid}_{j}.jpg"
            Image.open(io.BytesIO(blob)).convert("RGB").save(path, quality=95)
            refs.append(f"{cid}/{path.name}")
        entries.append({
            "id": cid,
            "prompt": casegen.frame_prompt(concept, i),
            "concept": concept,
            "coarse": coarse_map[concept],
            "kind": "control",
            "cohort": "common",
            "gt_refs": refs,
        })

    args.out.write_text(emit_yaml(entries, images_root=args.refs_dir))
    print(f"[make-cases] {len(entries)} cases -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
